feat: added BM extenxtion cartridge for Imgix
imgix/sf-commerce-cloud pull request #11
Opened 2021-09-24 11:22 UTC by SVPToptal

2021-09-24 12:12 UTC, frederickfogerty requested changes
`imagix` should be `imgix` - this is incorrect in the folder name and also in the `.project` file

2021-09-24 12:12 UTC, frederickfogerty commented on cartridges/bm_app_imagix_base/.project
> +    <name>bm_app_imagix_base</name>
```suggestion
    <name>bm_app_imgix_base</name>
```

2021-09-24 16:47 UTC, luqven commented
@SVPToptal could you please add a description of the change this PR encompasses?

I'm struggling just by reading the changes here to understand what committing this code would change for our Page Designer component.

I find it helpful when PRs that change behavior / UI in some way include a video. You can try out Vimeo's [extension](https://chrome.google.com/webstore/detail/vimeo-record-screen-webca/ejfmffkmeigkphomnpabpdabfddeadcb?hl=en) if you don't already have a good way of recording. If this change is easier to explain in a screen recording please feel free to do that instead.

2021-09-29 16:35 UTC, luqven requested changes
Hey @SVPToptal, a couple of comments.

1) Please make sure you have a clean commit history before asking for a review
2) Please make sure you use camel or snake case when naming files and folders to avoid spelling mistakes
3) Please fix the typo in `/cartridges/int_imgix_pd/cartridge/app_imgix_base_sfra.properties`
4) **Please let me know if the current directory structure is working on your end. If it's not, let me know if we need to change it as I suggest bellow.**

---
**First**
 I’ve cleaned up your commit history. Please make sure to familiarize yourself with GIT's interactive rebase to do this yourself in the future.

**Second**
I’ve fixed a spelling mistake for `imgrender` to `imagerenderer`. To avoid spelling mistakes like this, it's helpful to camel or snake case folder and file names. I’ve gone ahead and renamed the file and folder to `imageRenderer` for this reason.

**Third**
 In `/cartridges/int_imgix_pd/cartridge/app_imgix_base_sfra.properties`, `app_inix_base_sfra` was probably supposed to be `app_imgix_base_sfra`.

**Finally, and most importantly**
The current file structure looks like this:

```
├── cartridges
│   ├── app_imgix_base_sfra
│   │   └── cartridge
│   │       ├── app_imgix_base_sfra.properties
│   │       ├── experience
│   │       │   └── components
│   │       │       └── imgix
│   │       │           ├── testcomp.js
│   │       │           └── testcomp.json
│   │       └── templates
│   │           └── default
│   │               └── imgix
│   │                   └── image
│   │                       └── imgerender
│   │                           └── imagerender.isml
│   └── bm_app_imgix_base
│       └── cartridge
│           ├── experience
│           │   └── editors
│           │       └── custom
│           │           ├── tileCustomView.js
│           │           └── tileCustomView.json
│           └── static
│               └── default
│                   └── experience
│                       └── editors
│                           └── displayCustomView.js
```

Should it not instead look more like this?

```
├── cartridges
│   ├──app_imgix_base_sfra
│   │   └── cartridge
│   │       ├── app_imgix_base_sfra.properties
│   │       ├── experience
│   │       │   └── components
│   │       │       └── assets
│   │       │           ├── testcomp.js
│   │       │           └── testcomp.json
│   │       └── templates
│   │           └── default
│   │               └── experience
│   │                   └── components
│   │                       └── assets
│   │                           └── imageRender.isml
│   └──bm_imgix_pd
│      └── cartridge
│          ├── experience
│          │   └── editors
│          │       └── imgix
│          │           ├── tileCustomView.js
│          │           └── tileCustomView.json
│          └── static
│              └── default
│                  └── experience
│                      └── editors
│                          └── imgix
│                              └── displayCustomView.js
```

SFCC expects a very specific folder structure. If we don’t follow it, our component won’t work as expected. It seems to me like we need to change the file structure to better match what SFCC expects. 

Please let me know if you have any inclination as to whether or not that needs to be done.
----

To recap:

1) Please make sure you have a clean commit history before asking for a review
2) Please make sure you use camel or snake case when naming files and folders to avoid spelling mistakes
3) Please fix the typo in `/cartridges/int_imgix_pd/cartridge/app_imgix_base_sfra.properties`
4) **Please let me know if the current directory structure is working on your end. If it's not, let me know if we need to change it as I suggest above.**

2021-09-29 16:40 UTC, luqven requested changes
A couple of other questions

2021-09-29 16:40 UTC, luqven commented on cartridges/bm_app_imgix_base/cartridge/experience/editors/custom/tileCustomView.json
> +    "name": "IMGIX product view",
FYI, imgix should never be capitalized.

```suggestion
    "name": "imgix product view",
```

2021-09-29 16:40 UTC, luqven commented on cartridges/bm_app_imgix_base/cartridge/static/default/experience/editors/displayCustomView.js
> +    });
Are lines 19 - 28 doing anything? If not we should not commit them.

```suggestion
```

2021-09-29 16:40 UTC, luqven commented on cartridges/bm_app_imgix_base/cartridge/experience/editors/custom/tileCustomView.json
> +    "description": "Returns a selector for the recommenders available on the instance. Allows product-to-product recommender",
I'm not sure what this description means. Can you expand on this? What is a "selector for recommenders"?

2021-09-29 16:40 UTC, luqven commented on cartridges/bm_app_imgix_base/cartridge/experience/editors/custom/tileCustomView.js
> +'use strict';
I'm not sure what this file is doing. Can you explain what it does and why we need it? If it's not needed we shouldn't commit it.

2021-09-29 18:13 UTC, SVPToptal commented on cartridges/bm_app_imgix_base/cartridge/static/default/experience/editors/displayCustomView.js
> +    });
we will remove this future  if we not use this, now just added to test the component rendering flow for all

2021-09-29 18:15 UTC, SVPToptal commented on cartridges/bm_app_imgix_base/cartridge/experience/editors/custom/tileCustomView.js
> +'use strict';
all SFCC script file require this line, then only server can read this file. it's SFCC backend related.

2021-09-29 18:17 UTC, SVPToptal commented
As per the SFCC standard we use camelCase for Script and Controller files. for Folder and ISML  all should be on Small letter. i update the file accordingly.

2021-09-29 18:23 UTC, luqven approved these changes
LGTM 👍🏼 

I still think a discussion around the folder structure is necessary at some point in the future.

2021-09-29 18:30 UTC, SVPToptal commented
> `imagix` should be `imgix` - this is incorrect in the folder name and also in the `.project` file

Done the change, please review

2021-09-29 18:47 UTC, luqven commented
Apologies for all the force pushes here @SVPToptal, our branches got out of sync.

2021-09-29 18:48 UTC, merged