feat(search): use hooks to style on input focus and show recent queries
imgix/sf-commerce-cloud pull request #125
Opened 2021-12-02 18:56 UTC by luqven

> This PR stacks on #124 . It will be rebased onto `next` once that is merged in.

This PR styles the search bar on `blur` and `focus` so that it expands/collapses to show/hide the recent searches.

## Before this PR

- Search input field did not include recent search history
- The SourceSelect buttons did not span the width of their container

## After this PR

- Search bar expands to show recent history (up to 3 searches)
- Recent history is clickable
- SourceSelect buttons styling matches comps more closely

## Future work

- Add a search button under the search bar
- Add a clear button under the search bar
- Add hover styling to the recent searches
- Responsive styling for the search bar and the recent searches dropdown.

## VIdeo 📹 

https://user-images.githubusercontent.com/16711614/144484926-a13768fc-f185-4d20-bd1d-49a537e62cf8.mov

2021-12-03 07:51 UTC, frederickfogerty requested changes
This is cool! Snazzy hooks ✨

2021-12-03 07:51 UTC, frederickfogerty commented on frontend/src/components/buttons/Button.module.scss
> +  width: 100%;
I think this will interfere with `flex: 1 1 auto` - we should probably aim to a) use flexbox first, and if that doesn't work, b) set this property as a class override by passing down `className` to the button component

2021-12-03 07:51 UTC, frederickfogerty commented on frontend/src/components/forms/search/SearchBar.tsx
> +                  {" "}
Is this necessary?

2021-12-03 07:51 UTC, frederickfogerty commented on frontend/src/components/forms/search/SearchBar.tsx
> +import { useLocalStorage } from "./useLocalStorage";
Nice!

2021-12-03 07:51 UTC, frederickfogerty commented on frontend/src/components/forms/search/SearchBar.tsx
> +        <div className={isFocused ? styles.show : styles.hide}>
So I was playing around with this interaction locally, and I think it is also necessary to handle the case where the user clicks into the search modal. 

https://user-images.githubusercontent.com/615334/144565006-ab75153f-b2cc-473c-a287-61b0ac786ea6.mov

2021-12-03 16:26 UTC, luqven commented on frontend/src/components/forms/search/SearchBar.tsx
> +        <div className={isFocused ? styles.show : styles.hide}>
Interesting... I can't seem to replicate this behavior. For me, this closes when clicking anywhere outside the input area. Will investigate.

2021-12-03 16:32 UTC, luqven commented on frontend/src/components/buttons/Button.module.scss
> +  width: 100%;
@frederickfogerty Assuming this is addressed in #127?

2021-12-06 13:29 UTC, frederickfogerty commented on frontend/src/components/buttons/Button.module.scss
> +  width: 100%;
I don't think I removed this line - if you're happy with this I would prefer we revert this change

2021-12-07 00:22 UTC, luqven commented on frontend/src/components/forms/search/SearchBar.tsx
> +                  {" "}
Handled [further up](https://github.com/imgix/sf-commerce-cloud/pull/137/commits/f295a016593ab7fa30956cdfd13182f1aeca387a) the stack

2021-12-07 00:23 UTC, luqven commented on frontend/src/components/buttons/Button.module.scss
> +  width: 100%;
Handled [further up](https://github.com/imgix/sf-commerce-cloud/pull/137/commits/015d917f25bca3a7a85eae434019b1e828c00695) the sack.

2021-12-07 00:23 UTC, luqven commented on frontend/src/components/forms/search/SearchBar.tsx
> +        <div className={isFocused ? styles.show : styles.hide}>
Handled[ further up](https://github.com/imgix/sf-commerce-cloud/pull/133) the stack

2021-12-07 00:25 UTC, luqven commented
CI is breaking because of the `useFocus` hook. It's really more of a listing issue, and since other PRs in the stack use this hook, I feel more comfortable tackling the CI issue as the last commit in the stack. Hope that's alright.

2021-12-07 11:51 UTC, frederickfogerty approved these changes
LGTM

2021-12-07 11:55 UTC, merged