chore: add default params preference [f-10]
imgix/sf-commerce-cloud pull request #161
Opened 2021-12-17 09:29 UTC by frederickfogerty

## Before

There was no ability to add default parameters to product images that were being passed through

## After

Default parameters can be set on product images. Also I restructured the product images code a bit to make the fall-back case clearer.

2021-12-17 09:29 UTC, frederickfogerty commented
/annotate

2021-12-17 09:32 UTC, frederickfogerty commented
@luqven for some reason annotate isn't working here?

2021-12-17 13:14 UTC, luqven commented
> @luqven for some reason annotate isn't working here?

Weird.. will investigate.

2021-12-17 13:23 UTC, luqven commented on cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.js
> +                  : ""),
nice 👏🏼

2021-12-17 13:24 UTC, luqven approved these changes
lgtm

2021-12-17 13:38 UTC, luqven commented on cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.js
> +                  : ""),
Something strange is happening where the string interpolation just isn't taking place 🤔 
`https://zybp-003-sandbox.imgix.net/on/demandware.static/-/Sites-apparel-m-catalog/default/dw4ca75192/images/large/PG.52001DAN84Q.BLACKWL.PZ.jpg?${imgixDefaultParams}`

2021-12-17 13:43 UTC, luqven requested changes
We need to change these from ES6 template literals to something that SFCC plays nice with.

2021-12-17 13:43 UTC, luqven commented on cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.js
> +                  ? `?${imgixDefaultParams}`
Turns out SFCC doesn't like ES6 very much 
```suggestion
                  ? "?" + imgixDefaultParams
```

2021-12-17 13:43 UTC, luqven commented on cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.js
> +                ? `?${imgixDefaultParams}`
```suggestion
                  ? "?" + imgixDefaultParams
```

2021-12-17 13:48 UTC, luqven commented
@frederickfogerty Added to commits to fix a small bug and oversight. Hope that's alright 😉 .

2021-12-17 13:48 UTC, merged

2021-12-20 11:27 UTC, frederickfogerty commented
Thanks for updating this @luqven 🙌