chore: change font related px to em values
imgix/sf-commerce-cloud pull request #170
Opened 2022-01-07 17:13 UTC by luqven

This commit changes font-related `px` values to corresponding `em` values. This was asked for in the SFCC cartridge review.

Most of these `em` values assume a "base font size" of `16px`.

Some of the `em` values are not 1:1 with their previous `px` values. This was done because the 1:1 `em` value threw things off. I suspect this is because the "base font-size" for the element in question is actually different from `16px`.

## Before/After this commit

> Images can be a tad misleading since they're not all the same size. You can however tell little if anything has changed.

before
![asset-grid-before](https://user-images.githubusercontent.com/16711614/148580034-3a9ffa09-e047-4c09-9dfc-85ed4e5fb32a.png)
after
![asset-grid-after](https://user-images.githubusercontent.com/16711614/148580087-4e1d4128-f871-401f-bdc8-a204db41e566.png)
before
![source-select-before-2](https://user-images.githubusercontent.com/16711614/148580039-87b2b748-c78a-47ca-877b-c77d68094cf2.png)
after
![source-eselect-after-2](https://user-images.githubusercontent.com/16711614/148580095-549ce07d-18a4-45d6-87b6-4d7face16f06.png)
before
![source-select-before](https://user-images.githubusercontent.com/16711614/148580041-272b44d3-6fe8-4afb-a4dd-efd183e2b836.png)
after
![source-eselect-after](https://user-images.githubusercontent.com/16711614/148580094-e85576d6-6c7d-4ad5-ae62-eb3fafa60821.png)
before
![spinner-before](https://user-images.githubusercontent.com/16711614/148580043-261618bc-f4dc-49b9-8f61-f85d90898653.png)
after
![spinner-after](https://user-images.githubusercontent.com/16711614/148580093-b962ef19-20ea-44b6-a1a6-64239fc0f393.png)
before
![search-before](https://user-images.githubusercontent.com/16711614/148580045-0a2639ef-20bd-44dd-a0f1-07e604e62d17.png)
after
![search-after](https://user-images.githubusercontent.com/16711614/148580085-cae38aa0-c409-487c-9a3b-01ee1848180a.png)

2022-01-07 20:59 UTC, luqven commented
Current dependencies on/for this PR:
* main
  * **PR #170**  (this PR)
    * **PR #171** 

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-01-10 08:59 UTC, frederickfogerty requested changes
Thanks for doing this. I think we should use `rem` instead of `em` where possible - `em` suffers from the issue where nested `em`s get essentially stacked on top of each other, making it hard to nest components. This is maybe what was causing the issue for you with the peculiarities with converting to `em`s.

Also, I think if we make `line-height`s just multiples rather than `em` values, that should also be a little bit more maintainable. 

Open to hear your feedback here if you don't agree.

2022-01-11 17:36 UTC, frederickfogerty approved these changes
LGTM

2022-01-11 17:36 UTC, frederickfogerty commented
Merging this to push to the mother repo

2022-01-11 17:36 UTC, merged