feat: create modal component
imgix/sf-commerce-cloud pull request #185
Opened 2022-01-19 23:22 UTC by luqven

2022-01-19 23:22 UTC, luqven commented
Current dependencies on/for this PR:
* next
  * **PR #184** 
    * **PR #185**  (this PR)
      * **PR #187** 
        * **PR #186** 

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-01-20 13:55 UTC, frederickfogerty reviewed
LGTM so far

2022-01-20 13:55 UTC, frederickfogerty commented on frontend/src/components/layouts/Modal.tsx
> +        <Portal className="modalPortal">
Where is this class name defined?

2022-01-20 13:55 UTC, frederickfogerty commented on frontend/src/components/layouts/Modal.tsx
> +            className={`${styles.backdrop} ${open && "active"}`}
```suggestion
            className={`${styles.backdrop} ${open && styles.active}`}
```

2022-01-20 13:55 UTC, frederickfogerty commented on frontend/src/components/layouts/Modal.tsx
> +            <div className={`${styles.content} modal-content`}>{children}</div>
```suggestion
            <div className={`${styles.content} ${styles['modal-content']}`}>{children}</div>
```
could also be styles.modalContent, not sure

2022-01-20 15:49 UTC, luqven commented on frontend/src/components/layouts/Modal.tsx
> +            className={`${styles.backdrop} ${open && "active"}`}
🤦🏼‍♂️ 100%, nice catch.

2022-01-20 15:49 UTC, luqven commented on frontend/src/components/layouts/Modal.tsx
> +        <Portal className="modalPortal">
It'd not being used for anything. This really should be an `id` not a `className`.

2022-01-20 15:49 UTC, luqven commented on frontend/src/components/layouts/Modal.tsx
> +            <div className={`${styles.content} modal-content`}>{children}</div>
Yup nice catch forgot the update the class here as well.

2022-01-24 08:17 UTC, frederickfogerty requested changes
Seems like the outstanding comments haven't been resolved yet

2022-01-25 20:59 UTC, merged

2022-01-26 12:48 UTC, frederickfogerty reviewed
LGTM