feat: create frameless buttons
imgix/sf-commerce-cloud pull request #196
Opened 2022-01-22 00:12 UTC by luqven

2022-01-22 00:15 UTC, luqven commented
Current dependencies on/for this PR:
* next
  * **PR #184** 
    * **PR #185** 
      * **PR #193** 
        * **PR #192** 
          * **PR #197** 
            * **PR #194** 
              * **PR #191** 
                * **PR #201** 
                  * **PR #196**  (this PR)
                    * **PR #198** 
                      * **PR #199** 
                        * **PR #200** 
                          * **PR #195** 
      * **PR #187** 
        * **PR #186** 

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-01-24 12:36 UTC, frederickfogerty requested changes
I like the implementation here but I'm wondering about the purpose - we already have a `Button` component - can we work the functionality here into that component potentially?

2022-01-24 12:36 UTC, frederickfogerty commented on frontend/src/components/buttons/FrameButton/FrameButton.module.scss
> +  // storybook is bugging out and wont' let me remove the medium option
```suggestion
  // storybook is bugging out and won't let me remove the medium option
```

2022-01-24 17:38 UTC, luqven commented
> I like the implementation here but I'm wondering about the purpose - we already have a `Button` component - can we work the functionality here into that component potentially?

Yes, we do already have a `Button` module. The issue I was running into with it was frustrating enough though that I wanted to start from scratch:

- controlling the colors/size was more difficult and often different from the design guide examples
- controlling for behavior when there was no text/icon was more difficult and often the end result was not centered correctly
- Drop shadows, frames, etc could not be turned on/off easily depending on props, which meant I needed to use wrappers often.

The one functionality I'd like to bring over from the existing module is the `flat` prop. Otherwise, I think we'll be better served by this module moving forward.

The only outstanding concern I have with this module (which I still have to test) is whether or not we need to keep using `div` instead of `button`, as I'm doing where. I'm a fan of the semantic web but I do remember at one point we had an issue where using `button` caused some unnecessary `submit` event firing.

If you'd rather I backfill these changes into the existing button we can definitely do that instead. Let me know what you think.

2022-01-25 20:33 UTC, luqven commented
I'm going to merge in this module for now to unblock myself but definitely open to reverting to the existing module/porting this module features over.

2022-01-25 20:33 UTC, merged

2022-01-26 12:45 UTC, frederickfogerty commented
I understand your pain around the existing Button component, but without taking the effort to migrate the existing usages of the old Button component to this one, then we end up in a worse situation. I think we should definitely take time to ensure that we are just using one component rather than two.

2022-01-26 12:50 UTC, frederickfogerty reviewed
See PR comment