feat: create image and delete icons
imgix/sf-commerce-cloud pull request #199
Opened 2022-01-22 00:12 UTC by luqven

2022-01-22 00:15 UTC, luqven commented
Current dependencies on/for this PR:
* next
  * **PR #184** 
    * **PR #185** 
      * **PR #193** 
        * **PR #192** 
          * **PR #197** 
            * **PR #194** 
              * **PR #191** 
                * **PR #201** 
                  * **PR #196** 
                    * **PR #198** 
                      * **PR #199**  (this PR)
                        * **PR #200** 
                          * **PR #195** 
      * **PR #187** 
        * **PR #186** 

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-01-24 12:40 UTC, frederickfogerty requested changes
After removing `width` and `height` this should be good

2022-01-24 12:40 UTC, frederickfogerty commented on frontend/src/components/icons/Delete.tsx
> +        width="16"
Let's delete the `width` and `height` attributes

2022-01-25 20:30 UTC, merged

2022-01-26 12:48 UTC, frederickfogerty reviewed
LGTM