chore: refactor container-styles
imgix/sf-commerce-cloud pull request #244
Opened 2022-01-29 00:50 UTC by luqven

2022-01-29 00:50 UTC, luqven commented
Current dependencies on/for this PR:
* next
  * **PR #235** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/235" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #236** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/236" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #237** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/237" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #238** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/238" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #239** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/239" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #240** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/240" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #241** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/241" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #242** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/242" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                  * **PR #243** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/243" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                    * **PR #244** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/244" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-02-01 07:44 UTC, frederickfogerty requested changes
See inline comments

2022-02-01 07:44 UTC, frederickfogerty commented on frontend/src/components/card/AssetCard.tsx
> +    selectedAssetId === asset.id && styles.selected,
Does this not add `false` to the class list?

2022-02-01 21:10 UTC, luqven commented on frontend/src/components/card/AssetCard.tsx
> +    selectedAssetId === asset.id && styles.selected,
💯 , I'll refactor this so this doesn't set the false value as the class name

2022-02-01 21:36 UTC, merged