build: add root-dirs and export from root
imgix/sf-commerce-cloud pull request #248
Opened 2022-01-29 00:51 UTC by luqven

2022-01-29 00:51 UTC, luqven commented
Current dependencies on/for this PR:
* next
  * **PR #235** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/235" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #236** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/236" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #237** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/237" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #238** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/238" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #239** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/239" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #240** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/240" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #241** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/241" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #242** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/242" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                  * **PR #243** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/243" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                    * **PR #244** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/244" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                      * **PR #245** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/245" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                        * **PR #246** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/246" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                          * **PR #247** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/247" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                            * **PR #248** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/248" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-02-01 07:47 UTC, frederickfogerty requested changes
See inline comments

2022-02-01 07:47 UTC, frederickfogerty commented on src/cartridges/tsconfig.json
> +    "rootDirs": [
This will unfortunately break the `cartridges` build. I think we're going to have to find another way to sync the types from the projects. For now I think we can simply copy the file between projects.

2022-02-01 18:29 UTC, frederickfogerty approved these changes
Resolved offline

2022-02-01 21:35 UTC, merged