feat: add imgix sdk script
imgix/sf-commerce-cloud pull request #278
Opened 2022-02-07 13:29 UTC by frederickfogerty

This will give consumers of the products integration cartridge access to the js-core library to help them further modify their images.

Example usage in a custom component:
![image](https://user-images.githubusercontent.com/615334/152797141-969616f7-5fef-4e37-ab59-046da268b851.png)

with isml as:
```
<img src="${pdict.image_src}" />
```

Results in:
![image](https://user-images.githubusercontent.com/615334/152797632-8d1d4188-ca0a-4c73-a457-c128b19e436c.png)

2022-02-07 13:29 UTC, frederickfogerty commented
Current dependencies on/for this PR:
* next
  * **PR #278** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/278" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-02-08 22:21 UTC, luqven requested changes
See inline comments

2022-02-08 22:21 UTC, luqven commented on src/cartridges/int_imgix_products_sfra/cartridge/scripts/imgix/imgix.ts
> +import type IImgixClient from "@imgix/js-core";
This is failing on CI 🧐

2022-02-09 09:06 UTC, frederickfogerty commented on src/cartridges/int_imgix_products_sfra/cartridge/scripts/imgix/imgix.ts
> +import type IImgixClient from "@imgix/js-core";
Ah, I forgot to check in the dependency change ![dogscience](https://graphite-user-uploaded-assets.s3.amazonaws.com/default-memes/dogscience.jpg)

2022-02-09 17:14 UTC, luqven approved these changes
Commit lint is being commit lint about that `@` in the commit message 🤦🏼‍♂️. LGTM +1

2022-02-10 13:54 UTC, merged