feat: create attribute-form component
imgix/sf-commerce-cloud pull request #294
Opened 2022-02-14 06:21 UTC by luqven

2022-02-14 06:21 UTC, luqven commented
Current dependencies on/for this PR:
* next
  * **PR #283** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/283" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #284** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/284" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #285** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/285" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #286** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/286" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #290** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/290" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #288** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/288" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #287** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/287" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #289** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/289" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                  * **PR #292** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/292" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                    * **PR #293** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/293" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                      * **PR #294** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/294" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-02-14 10:54 UTC, frederickfogerty requested changes
See inline comments

2022-02-14 10:54 UTC, frederickfogerty commented on frontend/src/components/layouts/Modal.module.scss
> +  // background-color: white;
This should be removed before merging

2022-02-14 10:54 UTC, frederickfogerty commented on frontend/src/components/forms/attributes/AttributeForm.tsx
> +          // placeholder={placeholder}
What does this mean here? The placeholder is currently commented out.

2022-02-14 10:54 UTC, frederickfogerty commented on frontend/src/components/forms/attributes/AttributeForm.tsx
> +          // placeholder={placeholder}
This is also commented out

2022-02-15 16:54 UTC, luqven commented on frontend/src/components/forms/attributes/AttributeForm.tsx
> +          // placeholder={placeholder}
Yup apols. This was before I changed this into a controlled form. Will remove comments.

2022-02-15 16:54 UTC, luqven commented on frontend/src/components/layouts/Modal.module.scss
> +  // background-color: white;
100% thanks ![goodcatch](https://graphite-user-uploaded-assets.s3.amazonaws.com/default-memes/goodcatch.png)

2022-02-16 11:02 UTC, frederickfogerty reviewed
LGTM

2022-02-16 16:04 UTC, luqven commented
@frederickfogerty assuming this was closed in error?

2022-02-16 16:56 UTC, merged