feat: disable extension if product is locked
imgix/sf-commerce-cloud pull request #305
Opened 2022-02-23 05:20 UTC by luqven

This commit disabled the extension buttons if the product is `locked` on
SFCC. This ensures that the extension cannot be interacted with while
the product is locked.

It does this by storing a boolean tracking if the "Locked" label currently
reads as "Locked" or not.

This commit adds a `disabled` prop to the ProductImageContainer and
ProductPageImages components in order to achieve this.

2022-02-23 05:21 UTC, luqven commented
Current dependencies on/for this PR:
* next
  * **PR #305** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/305" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-02-23 09:50 UTC, frederickfogerty requested changes
See inline comments

2022-02-23 09:50 UTC, frederickfogerty commented on frontend/src/components/ExtensionApp.tsx
> +      document.querySelector(".table_detail_link")?.textContent === "Lock"
To me this seems a little brittle, in that in the future if the SF UI is updated, there's a potential for this to break. Could we potentially explore other ways to assess if the page is locked or not?

For some imagination, here are some options:
- Searching the page for the text "You haven't locked this product for editing"
- Using some more unique identifier, if it exists, for the locked product warning, or the link
- Searching for a link in the page with a corresponding `href` that will unlock the page.

2022-02-24 00:51 UTC, luqven commented on frontend/src/components/ExtensionApp.tsx
> +      document.querySelector(".table_detail_link")?.textContent === "Lock"
Thanks all good feedback. Will iterate on this. [![cathack](https://graphite-user-uploaded-assets.s3.amazonaws.com/default-memes/cathack.gif)](https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/305)

2022-02-24 01:07 UTC, luqven reviewed
Given that 

1) SFCC wouldn't want to break their own existing styling by adding a duplicate of this class

2) it's only present when the product is locked 

3) The class name is less likely to change than the help text IMHO, 

I think it's safe to base the locked state on the presence of the `.unlock_icon` class-name. 

Open to other suggestions as well of course.

2022-02-24 12:33 UTC, frederickfogerty approved these changes
Good enough for me for now. I think this is made better by the fact that if they *do* remove the icon or change the styling, the logic will revert to allowing the fields to be editable, so at least we won't be breaking the happy path.

2022-02-24 15:57 UTC, merged