fix: ensure sizes is never set to null/undefined
imgix/sf-commerce-cloud pull request #313
Opened 2022-02-24 13:36 UTC by frederickfogerty

Before this PR, in the Page Designer, the img tag's `sizes` attribute could be set to `undefined` or `null` depending on the situation. After this PR, two precautions were taken to ensure this can't happen.

1. The `model.image_sizes` data that is passed to the ISML template is only set if `content.sizes` actually has a useful value (i.e. not null-y and not an empty string)
2. In the ISML template, if no value is passed, before this would set `sizes` to `null`. Now, sizes is set to an empty string, which instructs browsers to fallback to the default value (`100vw`). I chose not to set `100vw` as the default since this allows browsers to behave smarter as they are more developed.

2022-02-24 13:36 UTC, frederickfogerty commented
Current dependencies on/for this PR:
* next
  * **PR #313** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/313" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-02-24 15:50 UTC, luqven requested changes
See inline comments

2022-02-24 15:50 UTC, luqven commented on cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js
> +    if (!fixedSize && content.sizes != null && content.sizes != "") {
Correct me if I'm mistaken, but I'm fairly certain that sizes will still be set to `null` here if `!fixedSize` and `!content.sizes`. The isml template will try to read the sizes key regardless if we set it here or not.

2022-02-24 16:56 UTC, luqven approved these changes

2022-02-24 16:56 UTC, luqven commented on cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js
> +    if (!fixedSize && content.sizes != null && content.sizes != "") {
When I tested this the `sizes` attribute would still get applied to the image tag, either with no value just `sizes` or `sizes="undefined"`. But if you're not seeing that it's possible (likely) I was setting the key somewhere and not realizing it. So feel free to disregard.

2022-02-25 09:23 UTC, frederickfogerty reviewed
I see the attribute on the image, but with this change it never has a value, it's just something like `<img src=".." sizes />`. I believe that this has no effect on the actual image. I'm going to merge this now since I think that this is okay behaviour, but happy to revisit if you think we should.

2022-02-25 09:26 UTC, merged