Imgix dev
imgix/sf-commerce-cloud pull request #62
Opened 2021-11-04 19:11 UTC by syedbadshah-toptal

2021-11-05 15:09 UTC, frederickfogerty approved these changes
LGTM, once the comments below have been addressed

2021-11-05 15:09 UTC, frederickfogerty commented on cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js
> + */
Is this comment accurate?

2021-11-05 15:09 UTC, frederickfogerty commented on cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.json
> +                ]
These configs should probably be removed

2021-11-05 16:18 UTC, luqven approved these changes
LGTM except the [package-lock.json file](https://github.com/imgix/sf-commerce-cloud/blob/97c8dbf5e8b81814525d5eb7f1033dae15bc6b4f/package-lock.json) shouldn't be committed. This repo already has a `yarn.lock`.

Let's remove that file before merging.

2021-11-05 16:53 UTC, luqven approved these changes
LGTM if Fred's feedback above has been resolved ☝🏼

2021-11-05 16:58 UTC, frederickfogerty requested changes

2021-11-05 16:58 UTC, frederickfogerty commented on cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js
> +module.exports.render = function (context) {
Now that js-core is integrated into the `next` branch, it's important those changes aren't overwritten. Therefore this needs to integrate those changes.

2021-11-05 17:31 UTC, frederickfogerty commented on cartridges/bm_imgix_pd/cartridge/experience/editors/imgix/imgixEditorTriggerBreakout.json
> +  "name": "Custom Car Editor Breakout",
This should be updated

2021-11-08 22:29 UTC, luqven commented
@frederickfogerty @syedbadshah-toptal I think we should close this in favor of #66 to avoid overwriting some of Fred's work in #64

2021-11-09 12:50 UTC, frederickfogerty commented
I agree with this @luqven 👍  @syedbadshah-toptal what do you think?

2021-11-09 18:40 UTC, closed without merging