feat: use sfcc events api in react app
imgix/sf-commerce-cloud pull request #66
Opened 2021-11-08 22:12 UTC by luqven

This PR uses the SFCC events API inside the FE react application. It mimmics the use of the events API from #62. Using the events API in these index files allows us to define it with specific use cases for each application. This brings in events API usage from #62.

2021-11-09 12:49 UTC, frederickfogerty requested changes
Looks good overal, just need to fix up a few things before merging

2021-11-09 12:49 UTC, frederickfogerty commented on cartridges/int_imgix_pd/cartridge/templates/default/imgix/imgixImage.isml
> +<!--- TEMPLATENAME: customBanner.isml --->
Can we please back out this change to using `imgixImage.isml` and revert to using the other template? Or copy the contents of the other template here? Thanks 🙌

2021-11-09 12:49 UTC, frederickfogerty commented on frontend/src/components/SidebarApp.tsx
> +export function App({ handleBreakoutOpen }: any) {
Let's fix this `any`

2021-11-09 12:49 UTC, frederickfogerty commented on frontend/src/index-breakout.tsx
> +        <App handleSubmit={handleSelect} />
Nice 👏

2021-11-09 12:49 UTC, frederickfogerty commented on frontend/src/tests/services/imgixAPIService.test.ts
> +  expect(requestedURI.getQueryParamValue("sort")).toBe("date_created");
I think you want `-date_created` here, since that will sort the results so the most recently created files are first (AFAIK)

2021-11-09 12:49 UTC, frederickfogerty commented on cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.json
> +          "id": "image_sel",
Let's revert this line, since it is incompatible with `cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js`

2021-11-09 12:49 UTC, frederickfogerty commented on cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.json
> +          "id": "altText",
Let's also revert these lines

2021-11-09 20:08 UTC, luqven commented on frontend/src/tests/services/imgixAPIService.test.ts
> +  expect(requestedURI.getQueryParamValue("sort")).toBe("date_created");
`-date_created` has a weird edge case where if the timestamps are exactly the same between a number of assets then the sort will happen randomly, making pagination unpredictable.

2021-11-09 20:17 UTC, luqven commented
@frederickfogerty [reverted](https://github.com/imgix/sf-commerce-cloud/pull/66/commits/546f27cce85f88b1ba957767a0685478b68f529b) to using `imageComponent.isml` and addressed some of your comments.

2021-11-09 20:59 UTC, luqven commented
Removed commit that checked in "working" react bundles. Will check that back in at the top of the stack where we can actually read from API keys.

2021-11-10 11:12 UTC, frederickfogerty commented
> Removed commit that checked in "working" react bundles. Will check that back in at the top of the stack where we can actually read from API keys.

What do you think about actually just using .gitignore for these files and instead only creating them locally, kind of like `dist` files in other libraries?

2021-11-10 11:13 UTC, frederickfogerty approved these changes
There's two things that I think need to be fixed here, but I think a higher priority is merging these PRs down to unblock development. Let's address these concerns in follow-up PRs

2021-11-10 11:13 UTC, frederickfogerty commented on frontend/src/index-sidebar.tsx
> +    }: any) => {
Let's fix up this `any` before merging

2021-11-10 11:13 UTC, frederickfogerty commented on frontend/src/tests/services/imgixAPIService.test.ts
> +  expect(requestedURI.getQueryParamValue("sort")).toBe("date_created");
What's the best path forward here then? Out of interest, what does IM on the web use? I personally think that going forward with sorting by any sort of ascending date/time is a non-starter, since it will be frustrating for most people I imagine.

2021-11-10 16:43 UTC, merged