chore: imgix default parameters passed via custom preference and fixe…
imgix/sf-commerce-cloud pull request #98
Opened 2021-11-16 22:42 UTC by syedbadshah-toptal

1. imgix default parameters passed via custom preference
2. Meta data updated with all the imgix custom preferences.

2021-11-17 00:16 UTC, luqven requested changes
I'm a little confused by these changes. Not sure what all of these attributes are supposed to be referencing/enabling. Moreover, I think we should include description fields on all of these attributes to ensure users know what they do.

2021-11-17 00:16 UTC, luqven commented on cartridges/bm_imgix_pd/cartridge/experience/editors/imgix/imgixEditorTrigger.js
> +    "ImgixapiKey"
imgix should never be capitalized. It's weird I know 😆 
```suggestion
    "imgixApiKey"
```

2021-11-17 00:16 UTC, luqven commented on cartridges/bm_imgix_pd/cartridge/experience/editors/imgix/imgixEditorTrigger.js
> +    "ImgixSourceId"
Not sure why we're changing this to `id` from `name`. Could you provide some background on this? 

Also same as above, `imgix` should never be capitalized.

2021-11-17 00:16 UTC, luqven commented on cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js
> +  const defaultParams = Site.getCurrent().getCustomPreferenceValue("ImgixDefaultParams");
nice 👏🏼

2021-11-17 00:16 UTC, luqven commented on metadata/imgix_data/meta/system-objecttype-extensions.xml
> +<metadata xmlns="http://www.demandware.com/xml/impex/metadata/2006-10-31">
Please remove the extra spacing added to this line.
```suggestion
<metadata xmlns="http://www.demandware.com/xml/impex/metadata/2006-10-31">
```

2021-11-17 00:16 UTC, luqven commented on metadata/imgix_data/meta/system-objecttype-extensions.xml
> +                <display-name xml:lang="x-default">IMGIX API BODY</display-name>
Why have all of these `display-name` (s) been changed to be all-caps? Can you provide some background for this?

2021-11-17 00:16 UTC, luqven commented on metadata/imgix_data/meta/system-objecttype-extensions.xml
> +                <display-name xml:lang="x-default">IMGIX API HEADERS</display-name>
Why have the `description` fields been removed? I think the user could benefit from understanding what these attributes do.

2021-11-17 00:16 UTC, luqven commented on metadata/imgix_data/meta/system-objecttype-extensions.xml
> +			<attribute-definition attribute-id="ImgixMethod">
Maybe I'm forgetting something we've discussed, but what is `ImgixMethod`?

2021-11-17 00:16 UTC, luqven commented on metadata/imgix_data/meta/system-objecttype-extensions.xml
> +                <display-name xml:lang="x-default">IMGIX VERSION</display-name>
This `display-name` seems to be incorrect. Should it not be `IMGIX DEFAULT PARAMS` is we're following the convention you've established here?

2021-11-17 13:52 UTC, frederickfogerty requested changes
LGTM after Luis's comments are addresses. For now, I've marked this as "Request Changes"

2021-11-17 13:52 UTC, frederickfogerty commented on cartridges/bm_imgix_pd/cartridge/experience/editors/imgix/imgixEditorTrigger.js
> +    "ImgixapiKey"
To clarify this suggestion, the name of the custom preference value should also be changed in the xml file

2021-11-17 13:52 UTC, frederickfogerty commented on cartridges/bm_imgix_pd/cartridge/experience/editors/imgix/imgixEditorTrigger.js
> +    "ImgixSourceId"
Could we probably just delete this whole line/preference? We aren't using this anywhere right?

2021-11-18 10:35 UTC, frederickfogerty approved these changes
LGTM 👍

2021-11-18 19:21 UTC, luqven commented on metadata/imgix_data/meta/system-objecttype-extensions.xml
> +                <display-name xml:lang="x-default">Imgix API Key</display-name>
non-blocking, but lets try not to capitalize imgix.
```suggestion
                <display-name xml:lang="x-default">imgix API Key</display-name>
```

2021-11-18 19:21 UTC, luqven commented on metadata/imgix_data/meta/system-objecttype-extensions.xml
> +                <description xml:lang="x-default">Imgix Default Params to be passed in URL</description>
```suggestion
                <description xml:lang="x-default">imgix Default Params to be passed in URL</description>
```

2021-11-18 19:21 UTC, luqven approved these changes

2021-11-18 19:22 UTC, luqven commented
LGTM, we can ignore the imgix capitalization for now. Just calling it to your attention for the future.

2021-11-25 09:36 UTC, merged