Hasan/add string attribute to set url
imgix/sf-commerce-cloud pull request #99
Opened 2021-11-16 23:25 UTC by syedbadshah-toptal

2021-11-17 00:29 UTC, luqven requested changes
Overall a good start.

I think we need to keep in mind that `content.image_data` and `imageUrl` are two very different URLs.

In fact, I'd almost rather we rename `imageURL` to `anchorTagUrl` or something along those lines. This will help keep those differences clear.

Let's discuss these changes some and we can then come back and fix this up.

2021-11-17 00:29 UTC, luqven commented on cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js
> +  // const rawImageUrl = (content.image_data && content.image_data.src) || "https://assets.imgix.net/amsterdam.jpg";
No need to leave this in if its not being used.
```suggestion
```

2021-11-17 00:29 UTC, luqven commented on cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js
> +  const rawImageUrl = model.imageUrl !== "#" ? model.imageUrl : "https://assets.imgix.net/amsterdam.jpg";
So I don't think we want to remove `content.image_data.src` here. The `imageUrl` and the `content.image_data.src` are two different things from what I understand.

One, `content.image_data.src` is the URL that points the image. The other, `imageUrl` is the URL that the image links to when clicked.

We don't want to pass the anchor tags URL to the `ImgixClient`. That client generates the image URL with src sets, sizes, etc that we need for the image. It can't do that if we give the anchor tag URL and not the image URL.

2021-11-17 00:29 UTC, luqven commented on cartridges/int_imgix_pd/cartridge/templates/default/experience/components/imgix/imageComponent.isml
> +  <isif condition="${pdict.imageUrl}">
What happens if we have an image that we don't want to link to anything externally? Will this `isif` keep it from rendering?

We should probably be able to handle images that don't have external links.

2021-11-18 10:34 UTC, frederickfogerty approved these changes
LGTM!

2021-11-18 19:20 UTC, luqven approved these changes

2021-11-25 09:41 UTC, merged